# ==========================================
# Mosquitto TLS/mTLS — PFE IoT Security TT
# ==========================================

# Listener TLS
listener 8883
protocol mqtt

# TLS settings
tls_version tlsv1.3
cafile /mosquitto/config/certs/ca-chain.crt
certfile /mosquitto/config/certs/mosquitto.crt
keyfile /mosquitto/config/certs/mosquitto.key

# mTLS : exiger certificat client
require_certificate true
use_identity_as_username true

# Sécurité
allow_anonymous false
# On utilise l'identité du certificat (CN) comme username.
# On gère l'autorisation via ACL.
acl_file /mosquitto/config/aclfile

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all

# Persistence MQTT (sessions/messages)
persistence true
persistence_location /mosquitto/data/