# =====================================================
# rsyslog.conf — Forward logs Mosquitto → Wazuh SIEM
# PFE IoT Security TT
# =====================================================

# Charger le module de surveillance de fichiers
module(load="imfile" PollingInterval="2")

# Surveiller le fichier de log Mosquitto
input(type="imfile"
      File="/mosquitto/log/mosquitto.log"
      Tag="mosquitto"
      Facility="local0"
      Severity="info"
      PersistStateInterval="100"
      StateFile="/var/spool/rsyslog/mosquitto-state")

# Forwarder TOUS les logs vers Wazuh Manager (UDP port 514)
# Wazuh SIEM : 192.168.40.10 (Zone SIEM VLAN 40)
*.* action(type="omfwd"
           Target="192.168.40.10"
           Port="514"
           Protocol="udp"
           Template="RSYSLOG_SyslogProtocol23Format")
